### ISSUE TITLE
The paper associated with this project

### ISSUE THREAD

**Issue by Kaixinguoer210** [starcolon/vor-knowledge-graph#6]
How can I obtain your phd paper about this project? C

**Comment by starcolon** [comment]
Hi @Kaixinguoer210 
This may surprise you. The project is not a part of academic work, instead more of a fun side project (it's an ongoing project btw).

**Comment by sriniraghu16** [comment]
While I run this command

"python3 build_knowledge.py --verbose --root root --limit 4"

I get this error

"Initialising knowledge graph database...
Traceback (most recent call last):
  File "build_knowledge.py", line 91, in <module>
    kb = Knowledge('localhost','vor','root',args['root'])
  File "/root/fastai/vor-knowledge-graph/pylib/knowledge/graph.py", line 23, in __init__
    self.__session = self.orient.connect(usrname,psw)
  File "/root/anaconda3/envs/fastai/lib/python3.6/site-packages/pyorient/orient.py", line 292, in connect
    return self.get_message("ConnectMessage") \
  File "/root/anaconda3/envs/fastai/lib/python3.6/site-packages/pyorient/orient.py", line 489, in get_message
    message_instance = _Message(self._connection)\
  File "/root/anaconda3/envs/fastai/lib/python3.6/site-packages/pyorient/messages/connection.py", line 17, in __init__
    super( ConnectMessage, self ).__init__(_orient_socket)
  File "/root/anaconda3/envs/fastai/lib/python3.6/site-packages/pyorient/messages/base.py", line 24, in __init__
    sock.get_connection()
  File "/root/anaconda3/envs/fastai/lib/python3.6/site-packages/pyorient/orient.py", line 52, in get_connection
    self.connect()
  File "/root/anaconda3/envs/fastai/lib/python3.6/site-packages/pyorient/orient.py", line 78, in connect
    " is not supported yet by this client.", [])
pyorient.exceptions.PyOrientWrongProtocolVersionException: Protocol version 37 is not supported yet by this client."

Pls help
