### ISSUE TITLE
Unhandled rejection SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by sriniraghu16** [starcolon/vor-knowledge-graph#8]
when I run this command,
" node visualise root"

I get this error,

================================
[Datasource] Processing :  { name: 'vor', mapper: [Function], output: 'graph-data.js' }
================================
Unhandled rejection SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /root/fastai/vor-knowledge-graph/visualise.js:218:12
    at tryCatcher (/root/fastai/vor-knowledge-graph/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/root/fastai/vor-knowledge-graph/node_modules/bluebird/js/release/reduce.js:155:18)
    at Object.gotAccum (/root/fastai/vor-knowledge-graph/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/root/fastai/vor-knowledge-graph/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/fastai/vor-knowledge-graph/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/root/fastai/vor-knowledge-graph/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/root/fastai/vor-knowledge-graph/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/root/fastai/vor-knowledge-graph/node_modules/bluebird/js/release/async.js:138:12)

Pls help

**Comment by starcolon** [comment]
Based on your output, the word space data `graph-data.js` should be written with 118 nodes and 100 links. Can you try opening `html/graph-universe.html`?

The second part of your output suggests that you don't have an index data generated beforehand. This can be done with `build_index.py`.

**Comment by sriniraghu16** [comment]
I tried opening "html/graph-universe.html" but could find it empty !! Also the "build_index.py" too seems to be empty. what can be done to overcome this?

**Comment by starcolon** [comment]
`build_index.py` will generate the index data onto your OrientDB. The output database will be created as `vorindex`. Can you check if it exists and whether it has some nodes/edges inside?
